name: Build App
on: [ workflow_dispatch ]
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
              with:
                repository: 'edesalto/bodapp'
                token: ${{ secrets.PAT }}
                ref: 'main'
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Build PWA
              run: npx ionic build --prod
            - name: Lists files
              run: ls -la
            - name: Fast FTP Action
              uses: anvil-solutions/Fast-FTP-Action@2.1.0
              with:
                server: genbri.com
                port: 21
                username: bodapp
                password: zB%8wo410