name: Build App
on: [ workflow_dispatch ]
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
              with:
                repository: 'edesalto/bodapp'
                token: ${{ secrets.PAT }}
                ref: 'main'
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Build PWA
              run: ionic build --prod
            - name: Lists files
              run: ls -la