name: Build App
on:
  push:
    branches:
    - main
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
              with:
                repository: 'edesalto/bodapp'
                ref: 'main'
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Lists files
              run: ls -la