name: Deploy Api
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm install
            - name: Tests
              run: npm run lint
            - name: Install zip
              run: sudo apt-get install zip -y
            - name: Zip API
              run: zip -r api.zip .
            - name: Publish build artifact
              uses: actions/upload-artifact@v4
              with:
                name: api.zip
                path: api.zip